---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x ANSIBLE0010 .
  flake8
platforms:
  - name: instance
    image: amazonlinux:2
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
  options:
    hosts: 'docker://instance'
